---
# main.yml for Jenkins installation role

- name: Download Jenkins repository
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  become: yes

- name: Add Jenkins GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  become: yes

- name: Install Jenkins package
  ansible.builtin.yum:
    name: jenkins
    state: present
  become: yes

- name: Enable Jenkins service to start on boot
  ansible.builtin.systemd:
    name: jenkins
    enabled: yes
  become: yes

- name: Start Jenkins service
  ansible.builtin.systemd:
    name: jenkins
    state: started
  become: yes

