---
# tasks/main.yml

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Ensure sources.list.d directory exists
  file:
    path: /etc/apt/sources.list.d
    state: directory
    mode: '0755'
  become: yes

- name: Upgrade the system
  apt:
    upgrade: dist
    state: latest
  become: yes

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - curl
    state: present
  become: yes

- name: Install containerd
  apt:
    name: containerd
    state: present
  become: yes

- name: Configure containerd to use systemd as the cgroup driver
  block:
    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'
      become: yes

    - name: Generate default containerd configuration
      command: containerd config default
      register: containerd_config
      become: yes

    - name: Write containerd configuration file
      copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: '0644'
      become: yes

    - name: Set SystemdCgroup to true in containerd config
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'
      become: yes

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted
    enabled: yes
  become: yes

- name: Install Kubernetes components
  block:
    - name: Add Kubernetes GPG key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        state: present
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      become: yes

    - name: Add Kubernetes repository
      lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
        create: yes
      become: yes

    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install kubelet, kubeadm, kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
      become: yes

    - name: Mark Kubernetes components on hold (using apt-mark)
      command: apt-mark hold kubelet kubeadm kubectl
      become: yes

- name: Disable swap
  block:
    - name: Turn off swap
      command: swapoff -a
      become: yes

    - name: Disable swap in fstab
      lineinfile:
        path: /etc/fstab
        regexp: '.*swap.*'
        line: '#\0'
      become: yes

- name: Load necessary kernel modules
  block:
    - name: Load overlay module
      modprobe:
        name: overlay
        state: present
      become: yes

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present
      become: yes

- name: Set required sysctl parameters for Kubernetes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }
  become: yes

